[network]
#port = 8082

[ui]
#background = "/home/user/Pictures/background.png"

#text_color.r = 0xcc
#text_color.g = 0xcc
#text_color.b = 0xcc
#text_color.a = 0xff

#matrix_color.r = 0xff
#matrix_color.g = 0x7e
#matrix_color.b = 0x00

#button_border_color.r = 0xcc
#button_border_color.g = 0xcc
#button_border_color.b = 0xcc
#button_border_color.a = 0xff

#add_modified_text = true
